name: Update Resume

on:
  schedule:
    - cron: 0 0 * * *
  push:
    branches: [main]
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Set up python
        uses: actions/setup-python@v4
        with:
          python-version: "3.11"
      - name: Download Linkedin scraper
        run: pip3 install git+https://github.com/tomquirk/linkedin-api.git
      - name: Fetch newest version of LinkedIn profile # run main.py
        run:
